AWSTemplateFormatVersion: "2010-09-09"
# SAM을 사용하겠다는 선언입니다.
Transform: AWS::Serverless-2016-10-31
Description: >
  My existing FastAPI project deployed with SAM.

Resources:
  # 'MyApiFunction'은 원하는 이름으로 바꿔도 됩니다.
  MyApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      # 코드가 있는 위치를 알려줍니다.
      # main.py가 루트에 있다면 '.'으로 지정합니다.
      CodeUri: .
      # 실행할 핸들러를 지정합니다. 'main.py' 파일 안의 'handler' 객체를 의미합니다.
      Handler: main.handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        # 모든 경로(/)와 모든 HTTP 메소드(ANY) 요청을 이 함수로 전달하라는 의미입니다.
        # 이렇게 해야 FastAPI 라우팅이 정상 작동합니다.
        CatchAll:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          GEMINI_API_KEY: "{{resolve:ssm:/webpurifier/GEMINI_API_KEY}}"
          CORS_ORIGINS: "{{resolve:ssm:/webpurifier/CORS_ORIGINS}}"
          STAGE: Prod
