"""Add password_hash to users

Revision ID: d8ae1de7be0e
Revises: 87d59d9f52e4
Create Date: 2025-10-21 11:47:08.910900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ae1de7be0e'
down_revision: Union[str, Sequence[str], None] = '87d59d9f52e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# alembic/versions/d8ae1de7be0e_...py

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # nullable=False 를 True로 변경합니다.
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True)) 
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
